// ==UserScript==
// @icon         https://thumb.cloud.mail.ru/weblink/thumb/xw1/NAX3/TrX2nGFzd?mt=1689107482000
// @name         👉UserStyles👈☭🇷🇺 Русификация
// @namespace    https://github.com/SkyK0T/UserScript
// @version      1.0
// @description  Русифицирует все сайты со стилями ☭🇷🇺👉UserStyles.world👉Uso.kkx.one👉UserStyles.org😈
// @author       Sky_
// @match        https://userstyles.world/*
// @match        https://uso.kkx.one/*
// @match        https://userstyles.org/*
// @match        https://openuserjs.org/*
// @match        https://userscript.zone/*
// @run-at       document-end
// @grant        none

/*
Userscript.Zone
https://www.userscript.zone/search?q=
UserStyles.world
https://userstyles.world/search?q=
Userscript.Zone`]:`https://www.userscript.zone/search?q=${e}`,}
UserStyles.world`]:`https://userstyles.world/search?q=${e}`,
OpenuserJS:`https://openuserjs.org/?q=$
*/


// ==/UserScript==

(function () {
    'use strict';
    const dict = {
"Install UserStyles with Stylus": "Установить в Stylus ❤️",
"Install with Stylus (Archive)": "Установить в Stylus ❤️",
"Install with Stylus": "Установить в Stylus❤️",
"Install Style": "Установить стиль ❤️",
"Install this style": "Установить стиль ❤️",
"Install from USO archive": "Установить USO❤️",
"Install from": "Установить с ️",
"USO archive": "архива USO❤️",
"View in uso.kkx.one": "Посмотреть на uso.kkx.one",
"Made with ❤️": "Сделано с любовью❤️",
"Installs this week": "Установок за неделю 👉",
"Sort by": "Сортировка",
"404 Not Found": "Страница не найдена",
"Don't have an account? Continue to ": "Нет аккаунта? Перейти на ",
" sign up page": " на страницу регистрации",
"sign up page": " на страницу регистрации",
"previous page.": " предыдущую страницу.",
"previous": " предыдущую",


"Brave, Vivaldi, Edge, Opera, Google Chrome and most web browsers besides Firefox and Safari.": "Brave, Vivaldi, Edge, Opera, Google Chrome и большинство веб-браузеров, кроме того Firefox и Safari.",

"Don't have an account? Continue to sign up page.": "Нет аккаунта? Перейти на страницу регистрации.",
"Keep me logged in (for up to 3 months)": "Держите меня в системе (до 3 месяцев)",
"See more styles on Explore page.": "👉Посмотреть больше стилей на странице обзора👈",
"Go to previous page ": "Перейти на предыдущую страницу",
"or visit our home page.": "или посетите главную страницу.",
"Explore": "👉Стили👈",
"Browse all available userstyles": "Посмотреть все доступные стили",
"See more styles on": "Посмотреть больше стилей тут ",
"Changelog": "Изменения",
"Mod Log": "Журнал модерации",
"Sign up failed": "Ошибка регистрации👿",
"Go to": "Перейти на",
"or visit our": "или посетите",
"Sign up": "Регистрация",
"Sign in": "Вход",
"Keyword": "Ключевое слово",
"Category": "Категория",
"Title": "Заголовок",
"Failed to count userstyles": "Не удалось подсчитать пользовательские стили",
"Failed to search for userstyles": "Не удалось выполнить поиск пользовательских стилей👿",
"Invalid page size": "Недопустимый размер страницы",
"Canonical": "Канонический",
"Search userstyles": "Поиск стилей",
"Search userstyles…": "Поиск стилей…",
"Search": "Поиск",
"Note: Signing in using usernames is disabled.": "Примечание: Вход в систему с использованием имен пользователей отключен.",
"Email address": "Почта",
"If there is an account associated with this email address, we'll send a password reset link to it.": "Если с этим адресом электронной почты связана учетная запись, мы отправим на нее ссылку для сброса пароля.",
"Make sure to check your spam folder.": "Проверьте папку со спамом",
"Confirm password": "Потвердить пароль",
"Password reset": "Пароль сброшен",
"Repeat password": "Повторить пароль",
"Forgot your Password?": "Забыли свой пароль?",
"Forgot your ": "Забыли свой ",
"password": "пароль",
"Password": "Пароль",
"Off topic": "Оффтоп",
"Not a review": "Нет просмотров",
"Reviewing own body parts": "Рассматривание частей собственного тела",
"defamation": "клевета",
"Defamation": "Клевета",
"Review bombing": "Терроризм",
"attaching other users": "💃💥атакует других пользователей",
"advertising": "Реклама",
"Must be 8–32 characters": "Пароль 8–32 символа",
"Forgot your Password?": "Забыт пароль?",
"using reviews for reporting": "использование обзора для составления репортов",
"3-star notification about code reuse?": "3-звездочка уведомления о повторном использовании кода?",
"ming verbal abuse and review bombing": "словесные оскорбления минга и рецензия на взрыв бомбы",
"Verbal abuse": "Словесные оскорбления",
"attaching site users": "💃💥атакует других пользователей",
"Inappropriate choice of words": "Неподходящий выбор слов",
"Defining kitchenware in reviews": "Определение кухонной утвари в обзорах",
"Gambling spam": "Реклама азартных игр",
"Advertising on review + biography": "Реклама в обзоре + биография",
"spam, advertisement via bio and style descriptions": "спам, реклама через биографию и описания стиля",
"Very questionable duplicate uploads": "Очень сомнительные повторяющиеся загрузки",
"An open-source community-driven alternative to userstyles.org ": "Альтернатива с открытым исходным кодом, управляемая сообществом, для userstyles.org ",
"that doesn't track you and works": "который вас не отслеживает и работает ",
"well with": " хорошо с расширением👉",

"About": "О нас",
"Free and open-source, community-driven website for browsing and sharing UserCSS userstyles.": "Бесплатный веб-сайт с открытым исходным кодом, ориентированный на сообщество, для просмотра пользовательских стилей UserCSS и обмена ими..",
"Email verification sent": "Отправлено подтверждение по электронной почте",
"Verification link has been sent to your email address.": "Ссылка для подтверждения была отправлена на ваш электронный адрес.",
"Your account will be created when you visit the verification link.": "Ваша учетная запись будет создана, когда вы перейдете по ссылке для подтверждения.",
"Free and open-source,": "Бесплатный и открытый исходный код,",
"community-driven platform for sharing and browsing UserCSS userstyles,": "платформа, управляемая сообществом, для обмена файлами и просмотра пользовательских стилей UserCSS,",
"and a replacement for": "и замена для",
"made by the userstyles community": "сделано с любовью❤️от сообщества UserStyles️❤️",
"Features": "👉 Функции️ 👈",
"What sets us apart from other platforms.": "Что отличает нас от других платформ.",
"Fennec Fox": "Фенёк Лисёнок",
"Invalid credentials.": "Недействительные учетные данные.",
"Reset password": "Сброс пароля",
"For OAuth users, use OAuth's email address to recover your account.": "Для пользователей OAuth используйте адрес электронной почты OAuth для восстановления своей учетной записи.",
"Enter your email address": "Введите почту",
"Send mail": "Отправить код на почту",
"e.g.": "пример",
"e.g. username@example.org": "Пример имя@пример.ru/com/org",
"Resources": "Ресурсы",
"Documentation": "Документация",
"FAQs": "Помощь",
"Content guidelines": "Рекомендации по содержанию",
"Security": "Безопастность",
"Licenses": "Лицензии",
"Support and links": "Поддержка и ссылки",
"Source code has over 10K characters, so we truncated it. You can inspect the full source code on install link": "Исходный код содержит более 10 тысяч символов, поэтому мы его сократили. Вы можете ознакомиться с полным исходным кодом по ссылке установить",

"Source code": "👉GitHub👉 Исходный код👈",
"Open an issue": "👉GitHub👉 Проблемы/предложения👈",
"Project roadmap": "👉GitHub👉 Дорожная карта👈",
"Chat on Matrix": "Чат в Matrix",
"Chat on Discord": "Чат в Дискорде",
"Support the project": "Поддержать проект",
"Create an account": "Создать аккаунт",
"Featured userstyles": "Рекомендуемые стили использования",
"Note: Signing in uses your email address, not username.": "Примечание: Для входа в систему используется ваш адрес электронной почты, а не имя пользователя.",
"Username": "Логин",
"Already have an account?": "У вас уже есть учетная запись?",
"Continue to the": "Продолжайте здесь ",
"Continue to": "Продолжайте здесь ",
"Don't have an account?": "У вас нет учетной записи?",
"sign in page": "страница входа в систему",
"Are you a bot?": "Вы бот?",
"I'm not a bot": "Сам ты бот",
"Privacy-first": "Конфиденциальность",
"Privacy Policy": "Конфиденциальность",
"Privacy policy": "Конфиденциальность",
"Privacy": "Конфиденциальность",
"We don't track you, and we won't sell, share, or mine your data.": "Мы не отслеживаем вас, и мы не будем продавать, делиться или добывать ваши данные",
"Tracker-free": "Без отслеживания",
"We won't let others track you either: no ads, no third-party cookies": "Мы также не позволим другим отслеживать вас: ни рекламы, ни файлов cookie сторонних производителей",
"Lightweight and fast": "Легко и быстро",
"We care about performance and aim to be as fast as possible.": "Мы заботимся о производительности и стремимся работать как можно быстрее.",
"User-friendly": "Удобно для пользователя",
"Built with accessibility and usability in mind from the start.": "Встроенная доступность и удобство использования с самого начала.",
"": "",
"Easy to get started": "Легко начать",
"Takes a couple of minutes to sign up and upload your first userstyle.": "Регистрация занимает пару минут и загрузите свой первый пользовательский стиль.",
"No vendor lock-in": "Нет привязки к поставщику",
"Host your userstyles anywhere with self-contained UserCSS format.": "Разместите свои пользовательские стили в любом месте с автономный формат UserCSS.",
"Stylus integration": "Stylus интеграция",
"Publish or push updates for your userstyles with a few clicks.": "Опубликуйте или нажмите опубликовать ваши пользовательские стили несколькими щелчками мыши.",
"Mirror userstyles": "Зеркала пользовательских стилей",
"Sync your userstyles from other places, including": "Синхронизируйте свои пользовательские стили из других мест, включая сайт с архивом стилей 👉 ",
"Community-driven": "На основе сообщества",
"Made as a joint effort between userstyle authors and users.": "Создано совместными усилиями авторов пользовательского стиля и пользователей.",
"Free/Libre Software": "Бесплатное программное обеспечение Libre",
"Licensed under": "Лицензировано по",
"the most protective copyleft license": " лицензии с наиболее защищенным авторским левым,свободная лицензия",
"An account is required in order to review userstyles": "Для просмотра пользовательских стилей требуется учетная запись",
"Write a review": "Написать отзыв",
"Successful email verification": "Почта успешно потверждена❤️",
"You've successfully verified your email address.": "Вы успешно подтвердили свой адрес электронной почты.❤️",
"Imported and mirrored from": "Импорт с этого источника 👉👉👉",
"Most installs": "Установок☝️большинство☝️",
"Least installs": "Установок👇меньшинство👇",
"Most views": "Просмотров☝️большинство☝️",
"Least views": "Просмотров👇меньшинство👇",
"Rating high to low": "Рейтинг☝️от высокого☝️",
"Rating low to high": "Рейтинг👇от низкого👇",
"Newest": "Создано👇недавно👇",
"Oldest": "Создано☝️давно☝️",
"Recently updated": "Обновлено☝️недавно☝️",
"Least recently updated": "Обновлено👇давно👇",
"Moderation log": "Журнал модерации",
"Read-only list of all moderation actions.": "Список всех действий модерации, доступных только для чтения.",
"Date and time": "Дата и время",
"Taken by": "Взятый",
"Action kind": "Вид действия",
"Action": "Действие",
"Affected user": "Затронутый пользователь",
"Reason": "Причина",
"Gambling advertisement spam": "😼Реклама азартных игр, спам😼",
"Spam": "😼Спам😼",
"(show all)": "показать всех",
"Default (show all)": "Показать всех",
"Removed users": "Удалённые пользователи",
"Removed styles": "Удалённые стили",
"Removed reviews": "Удалённые по причине",
"Default": "Стандарт",
"Remove user": "Удалённый пользователь",
"Remove style": "Удалённый стиль",
"Remove review": "Удалён по причине",
"Censored entry": "👉❤️👈зацензурено",
"Censored": "👉❤️👈зацензурено",
"Filter": "Фильтр",
"Duplicate uploads": "Дубликат",
"Empty userstyles with broken metadata": "Пустые пользовательские стили с неработающими метаданными",
"Empty userstyle": "Пустой стиль",
"no name": "нет имени",
"no metadata": "нет метаданных",
"Empty userstyles with no adequate names or metadata": "Пустые пользовательские стили без соответствующих имен или метаданных",
"of styles with meaningless names ": "о стилях с бессмысленными названиями",
"NSFW preview": "Порно превью",
"Was relying on Discord as a CDN": "Полагался на Discord как на CDN",
"Usage forbidden": "Использование запрещено",
"Broken due to relying on Discord as a CDN": "Сломан из-за использования Discord в качестве CDN",
"Unclear purpose": "Неясная цель",
"lacking adequate metadata": "отсутствие адекватных метаданных",
"Slightly older versions of #16175 from the same uploader": "Немного более старые версии # 16175 от того же загрузчика",
"Duplicate of": "Дубликат этого стиля",
"the same user": "одного и того же пользователя",
"Not a userstyle": "Не пользовательский стиль",
"Not original author": "Не оригинальный автор",
"No redistribution": "Никакого перераспределения",
"broken style": "сломанный стиль",
"Not a valid userstyle": "Недопустимый пользовательский стиль",
"UserScripts are not allowed": "Пользовательские скрипты не разрешены",
"We do not permit NSFW screenshots": "Мы не разрешаем делать скриншоты NSFW",
"A duplicate of the original Dark-WhatsApp": "Дубликат оригинального Dark-WhatsApp",
"Broken and irrelevant userstyle": "Сломанный и неуместный пользовательский стиль",
"Nothing to see here": "Здесь не на что смотреть",
"We don't allow UserScripts": "Мы не разрешаем использование пользовательских скриптов",
"Irrelevant, and not an userstyle.": "Неуместно, и это не пользовательский стиль.",
"Broken duplicate of ": "Сломаный дубликат ",
"Broken": "Сломаный",
"irrelevant": "неуместный",
"Irrelevant, и not an userstyle. Incorrect data was entered as well": "Не имеет значения, и не является стилем пользователя. Также были введены неверные данные.",
"Duplicate, not a userstyle": "Дубликат, а не пользовательский стиль",
"Invalid": "Недопустимый",
"Don't redistribute styles": "Не распространять стили",
"NO-REDISTRUBTION": "без распространения",
"NO-REDISTRIBUTION": "без распространения",
"from uso-archive": "из архива uso",
"We don't support userChrome.css styles": "Мы не поддерживаем стили userChrome.css",
"Violation of license terms from the original userstyle:": "Нарушение условий лицензии оригинальным пользовательским стилем:",
"license": "лицензия",
"Bad language": "Сквернословие",
"no redistribution": "без распространения",
"Inappropriate image": "Неподходящий образ",
"Redistribution of original code that's under non-permissive": "Перераспределение исходного кода, находящегося под запретом",
"Stolen from ": "Украдено у ",
"duplicate style from the same author": "дублирующий стиль от одного и того же автора",
"Not the original author": "Неоригинальный автор",
"info here": "инфо здесь",
"NSFW content": "🔞18+ контент🔞",
"global": "глобальный",
"Duplicate style from the same author": "дублирующий стиль от одного и того же автора",
"Older/almost same version of the style from the same author.": "Более старая / почти такая же версия стиля от того же автора.",
"There are no .btn-primary on example.com": "Нет .btn-primary на example.com",
"One of PimEyes duplicates": "Один из дубликатов Pim Eyes",
"Bad category": "плохая категория",
"distorted syntax": "искаженный синтаксис",
"description": "описание",
"Duplicate (": "Дубликат (",
"link instead of reuploading": "ссылка вместо повторной загрузки",
"Old duplicate of": "Старый дубликат ",
"Bad name": "плохое имя ",
"category,": "категория,",
"style version as new style": "версия стиля как новый стиль",
"original": "оригинал",
"Empty and broken userstyle": "Пустой и сломаный стиль",
"Old version of userstyle ": "Старая версия стиля",
"from the same author": "от этого автора",
"metadata header": "заголовок метаданных",
"~same code as in": "~ тот же код, что и в ",
"Duplicate userstyles": "Дубликат стиля ",
"Duplicate upload": "Загружен дубликат",
"Trojan making web pages white": "Троян делающий веб-страницы белыми",
"broken metadata": "неработающие метаданные",
"Moderation action": "Действие модерации",
"Reupload of": "Загружен повторно",
"invalid metadata": "с некоректными метаданными",
"url scope": "область действия URL-адреса",
"No adequate metadata": "Нет адекватных метаданных ",
"large spammy uploads": "большие спам-загрузки ",
"Details": "👉Детали👈",
"Author": "Автор ",
"License": "Лицензия ",
"Code size": "Размер 👉 ",
"Code checksum": "Контрольная сумма 👉 ",
"Source Code": "Исходный код",
"Copyright notice": "Авторские права",
"Copyright": "Авторские права",

"Homepage": "🏡",
"home": "🏠",
"Home": "🏠",
"Reviews": "👉Отзывы👈",
"Notes": "👉Заметки👈",
"Latest updates": "👉Изменения👈",
"Statistics": "👉Статистика👈",
"Statistics": "👉Статистика👈 ",
"Biography": "👉Биография👈 ",
"Links": "👉Ссылки👈 ",
"Userstyles": "👉Статистика👈 ",
"View on UserStyles.org": "Посмотреть на UserStyles.org",
"View JSON": "Просмотр JSON",
"Atom Feed": "Фид Atom",
"Learn how we calculate statistics": "Узнайте, как мы рассчитываем статистику ",
"in the FAQ": "в разделе ЧАСТО задаваемых вопросов ",
"Total views": "Общее количество просмотров 👉",
"Total installs": "Общее количество установок 👉",
"Weekly installs": "Еженедельные установки 👉",
"Weekly updates": "Еженедельные обновления 👉",
"Contributors": "👉Участники👈",
"rated ": "поставил ⭐ ",
"Browser-specific notes": "👉Примечания, относящиеся к конкретному браузеру👈",
"Chrome (and Edge, Vivaldi, &c.) users": "Пользователи Chrome, Edge, Vivaldi",
"👉👈": "👉👈",
"Userstyle doesn't have notes": "Пользовательский стиль не имеет заметок",
"notes": "заметки",
"years," : "года,",
"years"  : "года",
"year,"  : "год,",
"year"   : "год",
"months,": "месяца,",
"months" : "месяца",
"month"  : "месяц",
"month," : "месяц,",
"weeks," : "недель/и,",
"weeks"  : "недель/и",
"week,"  : "неделя,",
"week"   : "неделя",
"days,"  : "дней,",
"days"   : "дней",
"day"    : "день",
"day,"   : "день,",
"hours," : "часов,",
"hours"  : "часов",
"hour"   : "час",
"hour,"  : "час,",
"minutes ": " минут ",
"minutes,": "минут,",
"minute" : "минута",
"minute,": "минута,",
"Popular": "Популярное",
"New": "Новое",
"Trending": "В тренде",
"Search": "Поиск",
"Login": "Войти",
"Register": "Регистрация",
"Logout": "Выйти",
"Profile": "Профиль",
"Settings": "Настройки",
"Install": "Установить",
"Installed": "Установлено👉 ",
"Updated at": "Обновлено в👉 ",
"Updated": "Обновлено👉 ",
"Update": "Обновить",
"Uninstall": "Удалить",
"Installs": "Установок👉 ",
"Comments": "👉Комментарии👈",
"Description" : "👉Описание👈",
"Preview": "👉Предпросмотр👈",
"Screenshots": "👉Скриншоты👈",
"Stats": "👉Статистика👈",
"Submit": "Отправить",
"Save Changes": "Сохранить изменения",
"Cancel": "Отмена",
"Edit": "Редактировать",
"Delete": "Удалить",
"Report": "Пожаловаться",
"Reply": "Ответить",
"More": "Ещё",
"Less": "Свернуть",
"Show more": "Показать ещё",
"Show less": "Скрыть",
"Loading...": "Загрузка…",
"No results found": "Ничего не найдено",
"Create style": "Создать стиль",
"My styles": "Мои стили",
"Favorites": "Избранное",
"Following": "Подписки",
"Followers": "Подписчики",
"Dark mode": "Тёмная тема",
"Light mode": "Светлая тема",
"Last updated": "Последнее обновление",
"Created at": "Создано в👉 ",
"Created": "Создано👉 ",
"Total": "Всего",
"total": "Всего",
"No reviews yet": "Пока отзывов нет🥺👉👈 ",
" views": " просмотров ",
" views": " просмотров ",
"Views": "Просмотров ",
"installs": "установок",
"updates": "обновления",
"daily": "сегодняшние",
"weekly": "недельные",
"No rating": "Нет рейтинга",
"ago": "назад",
" by ": " от ",
" By": " от",
" by": " от",
" page": " страницу",
"Style not found": "Стиль не найден🥺",
"UserStyles.org Archive": "👉Архив UserStyles.org👈",
"Additional info": "👉Дополнительная информация👈",
"If you want to upload your own userstyle, this is the place.": "Если вы хотите загрузить свой собственный пользовательский стиль, то это подходящее место",
"Applies to": "Применяется к сайту",
"Rating": "Рейтинг",
"Categories": "👉Категории👈",
"Installs this week": "Установлено за неделю",
"* - Brave, Vivaldi, Edge, Opera, Google Chrome и most web browsers besides Firefox and			Safari.": "Brave, Vivaldi, Edge, Opera, Google Chrome и большинство веб-браузеров, кроме того Firefox и Safari.",
" at ": " в ",
"Most popular": "Популярное",
"By @": "Автор",
"USO-Archive is an ad- and spyware-free mirror of": "USO-Archive uso.kkx.one - это зеркало сайта, не содержащее рекламы и шпионских программ, в отличие от этого сайта 👉 ",
"Data": "Данные",
"Chromium-based": "Chromium база",

"Since then, it is actively sharing your entire non-anonymized browsing history demo with them, assuming you ever clicked on one of the flashy": "С тех пор он активно делится с ними всей вашей демонстрацией неанонимизированной истории посещенных страниц, предполагая, что вы когда-либо нажимали на одну из ярких кнопок",
" Currently, it still breaks store policies, yet is not banned for unknown to me reasons": "Он и в настоящее время по-прежнему нарушает политику магазина, но не забанен по неизвестным мне причинам",
"It initially did this without even asking for consent, and was banned from extension stores afterwards": "Изначально он делал это, даже не спрашивая согласия, и впоследствии был запрещен в магазинах расширений",
"This website only works with the Stylus extension, which is an open-source privacy-friendly fork of the now-malicious Stylish extension.": "Этот веб-сайт работает только с расширением Stylus, которое является открытым исходным кодом, обеспечивающим конфиденциальность, ответвления ныне вредоносного расширения Stylish",


"Agree ": "Согласится ",
"buttons.": " ",
"USO-Archive does not collect any personal data": "USO-Archive не собирает никаких персональных данных",
"Consider uninstalling the malicious Stylish extension.": "Рассмотрите возможность удаления вредоносного расширения Stylish.",
" In 2016, with no input from the userbase,": "В 2016 году без ввода данных из базы пользователей, ",
"through some guy,": "через какого-то парня,",
"pretending to be an independent developer,": "выдававшего себя за независимого разработчика,",
" it basically was sold to a shady web analytics company, Similarweb.": "   оно было продано сомнительной компании по веб-аналитике Similarweb.",
"tg - @": "Telegram 👉 https://t.me/s/",
"tg @": "Telegram 👉 https://t.me/s/",
" Before": " Было",
"Before": "Было",
" After": "Стало",
" Both": "И то , и другое",
"Information": "Информация",
"Recommended Styles": "Рекомендуемые стили",
"APPLIES TO": "Применяется к сайту",
"DESCRIPTION": "Описание",
"January": "Январь",
"February": "Февраль",
"March": "Март",
"April": "Апрель",
"May": "Май",
"June": "Июнь",
"July": "Июль",
"August": "Август",
"September": "Сентябрь",
"October": "Октябрь",
"November": "Ноябрь",
"December": "Декабрь",
"Monday": "Понедельник",
"Tuesday": "Вторник",
"Wednesday": "Среда",
"Thursday": "Четверг",
"Friday": "Пятница",
"Saturday": "Суббота",
"Sunday": "Воскресенье",
"Jan": "Январь","Feb": "Февраль","Mar": "Март","Apr": "Апрель","May": "Май","Jun": "Июнь","Jul": "Июль","Aug": "Август","Sep": "Сентябрь","Oct": "Октябрь","Nov": "Ноябрь","Dec": "Декабрь",
"Mon": "Понедельник","Tue": "Вторник","Wed": "Среда","Thu": "Четверг","Fri": "Пятница","Sat": "Суббота","Sun": "Воскресенье",
"Personal Info": "Персональная информация",
"Create Style": "Создать стиль",
"Create!": "Создать",
"Go on and create": "Продолжайте и создайте",
"your first style": " свой первый стиль",
"DISPLAY NAME": "Имя",
"E-MAIL": "Почта",
"HOME URL": "Мой сайт",
"home url": "Адрес сайта",
"PAYPAL EMAIL": "Почта PayPal",
"ABOUT": "О нас",
"About": "О нас",
"Display Email": "Показывать почту",
"Go Pro": "Задонатить скамеру",
"Yearly": "Ежегодно",
"Monthly": "Ежемесячно",
"Proceed": "Продолжайте🤡",
"Money Back Guarantee": "возврата денег 😀",
"anytime": "в любое время",
"Get an Ads-free experience": "Убираем рекламу",
"Unlock exclusive Pro Styles": "Эксклюзивные Бро стили",
"Join our VIP community": "Присоединяйтесь к нашему VIP-сообществу",
"to unlock": "чтобы разблокировать",
"exclusive designs, first access to new": "эксклюзивные дизайны, первый доступ к новым",
"features, VIP support when creating": "функциям, VIP-поддержка при создании ",
"your own designs": "ваших собственных дизайнов",
"Tips for making user styles": "Советы по созданию пользовательских стилей",
"Give your style a cool name": "Дайте своему стилю классное название",
"Create your own style": "Создайте свой собственный стиль",
"Style Code": "Код стиля",
"Style Info": "Информация о стиле",
"Appearance": "Внешний вид",
"To specify which URLs will have the styles applied,": "Чтобы указать, к каким URL-адресам будут применены стили,",
"use the Mozilla @-moz-document format help": "используйте справку по формату Mozilla @-moz-document",
"Style Name *": "Имя стиля *",
"URL (optional)": "URL (опционально)",
"Save and Publish Your Style!": "Сохранить и опубликовать",
"(optional)": "(опционально)",
"": "",
"": "",
"Top Rated": "Топ в рейтинге",
"website themes that make the internet entirely yours": "темы веб-сайтов, которые делают интернет полностью под ваш вкус",
"Themes, Skins & Backgrounds": "Темы, Скины & Фон",
"Style with custom themes! Change the background, color, schemes, fonts, and more! Share your own themes too!": "Создавайте собственные темы! Меняйте фон, цвет, схемы, шрифты и многое другое! Также делитесь своими созданными темами!",
"ALL RIGHTS RESERVED": "Все права защищены",
"Help": "Помощь",
"General": "Главная",
"Stylish Mobile": "Stylish для телефона",
"Terms of use": "Условия использования",
"All categories": "Все категории",
"Contact us": "Связь",
"Thanks": "Спасибки❤️",
"Sent!": "Отправить!",
"What are we styling?": "Что мы стилизуем?",
"Jot something down": "Запишите что -нибудь",
"NOTES": "Примечания",
"DATE CREATED": "Дата создания",
"LAST UPDATED": "Дата обновления",
"SHOW CSS": "Показать код",
"Check it out": "Проверить на применяемом сайте",
"Added": "Добавлено",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"Cursor Styles": "Курсор Styles",
"Add Pro Style": "Добавить про стиль",
"Pro": "Про",
"STYLE": "Стиль",
"your": "для твоего",
"Save": "Сохранить",
"save": "сохрани",
"Skip": "Пропустить",
"Code": "Код",
"Copy": "Копировать",
};

    // ────────────────────────────────────────────────────────────────
    // Специальные правила для дат "Updated X time ago"
    // ────────────────────────────────────────────────────────────────
    const timeUnits = {
        "year"   : "год",
        "years"  : "года",
        "year,"  : "год,",
        "years," : "года,",
        "month"  : "месяц",
        "months" : "месяца",
        "month," : "месяц,",
        "months,": "месяца,",
        "week"   : "неделя",
        "weeks"  : "недели",
        "week,"  : "неделя,",
        "weeks," : "недели,",
        "day"    : "день",
        "days"   : "дня",
        "day,"   : "день,",
        "days,"  : "дня,",
        "hour"   : "час",
        "hours"  : "часа",
        "hour,"  : "час,",
        "hours," : "часа,",
        "minute" : "минута",
        " minutes ": " минут ",
        "minute,": "минута,",
        "minutes,": "минуты,",
    };

    // ────────────────────────────────────────────────────────────────
    // Основная функция обработки текста
    // ────────────────────────────────────────────────────────────────
    function translateNode(node) {
        if (node.nodeType !== Node.TEXT_NODE) {
            if (['INPUT','TEXTAREA','SCRIPT','STYLE'].includes(node.tagName)) return;
            for (let child of node.childNodes) translateNode(child);
            return;
        }

        let txt = node.nodeValue.trim();
        if (txt.length < 3) return;

        let originalTxt = txt;
        let changed = false;

        // 1. Обычные замены из словаря
        for (const [en, ru] of Object.entries(dict)) {
            if (txt.includes(en)) {
                txt = txt.replaceAll(en, ru);
                changed = true;
            }
        }

        // 2. Специальная обработка "Updated X time ago" → "Обновлено X время назад"
        if (txt.includes("Обновлено") || txt.includes("Updated")) {
            // Убираем "Updated" если осталось
            txt = txt.replace(/Updated\s*/i, "Обновлено ");

            // Добавляем пробел после "Обновлено" если его нет
            txt = txt.replace(/Обновлено([^ ])/g, "Обновлено $1");

            // Переводим единицы времени
            for (const [enUnit, ruUnit] of Object.entries(timeUnits)) {
                if (txt.includes(enUnit)) {
                    txt = txt.replaceAll(enUnit, ruUnit);
                    changed = true;
                }
            }

            // Финально заменяем "ago" → "назад" (если не заменилось раньше)
            txt = txt.replace(/\s*ago\b/gi, " назад");
        }

        if (changed && txt !== originalTxt) {
            node.nodeValue = txt;
        }
    }

    // Первый запуск
    translateNode(document.body);

    // Отслеживание новых элементов
    new MutationObserver(mutations => {
        for (const mut of mutations) {
            for (const node of mut.addedNodes) {
                if (node.nodeType === 1 || node.nodeType === 3) {
                    translateNode(node);
                }
            }
        }
    }).observe(document.body, {
        childList: true,
        subtree: true
    });

    console.log("[USW Русский] — да");
})();
